// English text. Facts (links, numbers, stacks) are in shared.js.
window.PORTFOLIO_CONTENT = window.PORTFOLIO_CONTENT || {};
window.PORTFOLIO_CONTENT.en = {
  role: "Data Engineer",
  headline: ["I turn raw data", "into working systems."],
  roles: [
    "real-time data pipelines",
    "cloud data warehouses",
    "ML-powered intrusion detection",
    "dashboards people use",
  ],
  intro:
    "Computer Engineering graduate (King Khalid University, GPA 4.11/5) building end-to-end data pipelines — from live ingestion with Kafka and PySpark to cloud warehouses on AWS and the dashboards on top.",
  about:
    "I like projects that go all the way from raw data to something people can use. I've streamed live market prices through Kafka and Spark into S3 and Redshift, modelled sales data into a star-schema warehouse for Power BI, and trained a Random Forest on 2.8 million network flows to catch attacks on a Raspberry Pi. Every project ships with tests, CI and a README someone else can follow.",
  location: "Saudi Arabia",

  stats: {
    gpa: "GPA — Computer Engineering, King Khalid University",
    flows: "Network flows used to train EdgeGuard's classifier",
    trades: "Live BTC trades processed by MARKET_OS in one run",
    certs: "Certifications and professional accreditations",
  },

  services: [
    { icon: "flow", title: "Streaming data pipelines", text: "Kafka producers, PySpark Structured Streaming, Parquet on S3 and incremental loads into Redshift or PostgreSQL.", size: "wide" },
    { icon: "database", title: "Data warehousing & BI", text: "Star schemas with SCD type 2, idempotent ETL/ELT and Power BI models with DAX." },
    { icon: "brain", title: "Machine learning", text: "scikit-learn and PyTorch, from exploratory analysis to evaluated, deployed models." },
    { icon: "shield", title: "Network security & edge AI", text: "Snort 3 signatures combined with an ML classifier running live on a Raspberry Pi 5.", size: "wide" },
    { icon: "cloud", title: "Cloud & DevOps", text: "AWS (S3, Redshift, EC2, IAM), Docker Compose, Terraform and GitHub Actions CI.", size: "full" },
  ],

  projects: {
    "market-os": {
      title: "MARKET_OS — Real-Time Market Data Pipeline",
      text: "Streams live Bitcoin trades from Binance and stock quotes from Alpha Vantage through Kafka and PySpark into S3 and Redshift, flags price spikes, and visualises everything on a live dashboard.",
      highlights: ["206,842 BTC trades processed in one run", "Dual-region: S3 eu-north-1 + Redshift us-east-1"],
      problem: "Market data arrives from different sources, in different formats and at different speeds. I wanted a single pipeline that takes live ticks all the way to an analytics warehouse and a dashboard.",
      built: [
        "A unified Kafka producer layer ingesting the Binance WebSocket and the Alpha Vantage API.",
        "PySpark Structured Streaming jobs that clean and validate records from both sources, and flag any trade more than 0.5% away from the previous batch's median price.",
        "Parquet files in an S3 data lake (eu-north-1), loaded incrementally into Redshift Serverless (us-east-1).",
        "A Streamlit dashboard that refreshes every 30 seconds.",
      ],
      results: [
        "Fully operational end to end: 206,842 BTC trades ingested and visualised in a single run.",
        "pytest suite and GitHub Actions CI, including a Docker image build check.",
        "A documented 24/7 deployment on AWS EC2 that swaps Redshift for PostgreSQL, avoiding Redshift Serverless costs that can pass $1,000 a month.",
      ],
    },
    edgeguard: {
      title: "EdgeGuard — ML Intrusion Detection & Risk Assessment",
      text: "Graduation project at King Khalid University: a hybrid IDS on a Raspberry Pi 5 that combines Snort 3 rules with a Random Forest classifier and scores every threat from 0 to 100.",
      highlights: ["Trained on 2.8M labelled flows, 78 features", "Watch the live demo ▶"],
      problem: "Signature-based detection misses attacks it has no rule for, and an ML model alone can be hard to trust. EdgeGuard layers both so each one covers the other's blind spots — on a small, low-cost device.",
      built: [
        "A Random Forest classifier in scikit-learn, trained on 2.8 million labelled CICIDS2017 flow records with 78 engineered features.",
        "Five traffic classes: BENIGN, PortScan, Brute Force, DoS and Web Attack.",
        "A hybrid pipeline that runs Snort 3 signature rules alongside the classifier.",
        "A risk engine that merges ML predictions and Snort alerts into one 0–100 score across five severity tiers.",
        "A Flask dashboard with a REST API and auto-refresh.",
      ],
      results: [
        "Live demo on a Raspberry Pi 5: an nmap SYN scan is detected and scored in real time.",
        "An automated evaluation script that benchmarks predictions against labelled CICIDS2017 test flows per attack category.",
      ],
    },
    salesdw: {
      title: "SalesDW — Sales Analytics Platform",
      text: "A self-hosted sales data platform: an ETL that adapts to new files and column names, a PostgreSQL star schema, a FastAPI ingest API and a Power BI reporting layer.",
      highlights: ["40+ DAX measures", "Unit + end-to-end tests in CI"],
      problem: "Sales data comes from point-of-sale exports, web shops and spreadsheets, each with its own column names. Reports break whenever a source changes.",
      built: [
        "An ETL that detects file types and entities automatically and maps column aliases through config instead of code.",
        "A PostgreSQL star schema with SCD type 2 customers and products, and late-arriving dimension handling.",
        "A folder watcher plus a FastAPI REST API for uploads, JSON records and run monitoring.",
        "Power BI connection guide, theme and 40+ DAX measures; Terraform for an Azure VM with nightly backups.",
      ],
      results: [
        "New columns, renamed headers and late or corrected data are handled without code changes.",
        "Unit and end-to-end tests against real PostgreSQL in GitHub Actions.",
      ],
    },
    kaust: {
      title: "KAUST AI — Machine Learning Labs",
      text: "Fifteen notebooks from the KAUST AI program (passed two levels): EDA, regression, classification, neural networks and unsupervised learning on real Kaggle datasets.",
      highlights: ["R² 0.975 on advertising-sales regression", "94.5% accuracy on MNIST with PyTorch"],
      problem: "A structured program to go from classical machine learning to deep learning, on real datasets rather than toy examples.",
      built: [
        "Regression and classification with scikit-learn, XGBoost, CatBoost and LightGBM.",
        "Neural networks in PyTorch for tabular data, MNIST and CIFAR-10.",
        "PCA, t-SNE, K-Means and autoencoders for unsupervised learning.",
      ],
      results: [
        "R² 0.975 predicting sales from advertising budgets.",
        "94.5% validation accuracy on MNIST and 90.8% on weather-type classification.",
        "95% accuracy on multi-class air-quality classification.",
      ],
    },
    portfolio: {
      title: "This Portfolio",
      text: "A hand-built bilingual site with a Pac-Man style canvas background, live GitHub data and an interactive EdgeGuard demo. No frameworks, no build step.",
      highlights: ["English / Arabic with right-to-left layout", "Live data from the GitHub API"],
      problem: "I wanted a portfolio that shows how I build, not just what I've built — and that works for recruiters in English and Arabic.",
      built: [
        "Vanilla JavaScript and Canvas, organised into small single-purpose files.",
        "All content in data files, rendered in English or Arabic with a right-to-left layout.",
        "Live repository data from the GitHub API, cached per visit.",
      ],
      results: ["Runs straight from a folder or on GitHub Pages, and respects reduced-motion settings."],
    },
  },

  edgeguard: {
    levels: { normal: "Normal", low: "Low", medium: "Medium", high: "High", critical: "Critical" },
    descriptions: {
      BENIGN: "Normal traffic. Nothing to report.",
      PortScan: "Someone is probing which ports are open — often the first step before an attack. In the live demo this is an nmap SYN scan, also caught by a Snort rule:",
      "Brute Force": "Repeated login attempts trying to guess a password.",
      DoS: "A flood of traffic trying to make a service unavailable.",
      "Web Attack": "Attacks on web applications such as SQL injection or XSS. Always treated as critical.",
    },
  },

  journey: [
    { title: "B.Sc. Computer Engineering", place: "King Khalid University", period: "2021 – 2026", text: "Graduated with a GPA of 4.11 / 5.00. Graduation project: EdgeGuard, an ML-based intrusion detection and risk assessment system." },
    { title: "KAUST AI Certificate", place: "King Abdullah University of Science and Technology", period: "Nov – Dec 2025", text: "Completed two levels of hands-on AI training: classical machine learning, gradient boosting and deep learning with PyTorch." },
    { title: "Trainee — Subscriber Management", place: "Saudi Electricity Company · Abha", period: "Jun 2024", text: "A one-week placement with the Subscriber Management department, mapping and documenting how customer issues move between the central office and the branches until they are resolved." },
  ],

  certifications: {
    "ibm-de": { title: "IBM Data Engineering Professional Certificate", text: "Data pipelines, ETL, SQL and NoSQL databases, data warehousing and big-data tools." },
    pl300: { title: "Microsoft PL-300: Power BI Data Analyst", text: "Preparing, modelling and visualising data in Power BI with DAX and Power Query." },
    kaust: { title: "KAUST AI Certificate", text: "Passed two levels · Nov – Dec 2025." },
    sce: { title: "Professional Accreditation — Engineer", text: "Computer Engineering · accredited since Feb 2026, valid until Aug 2027." },
    "kaust-python": { title: "Prerequisite Courses of AI — Python Basics", text: "Python foundations for the KAUST Academy AI track." },
  },

  // Shown when a GitHub repository has no description of its own
  repoDescriptions: {
    "business-management-project": "SalesDW: self-hosted sales analytics platform with an adaptive ETL, a PostgreSQL star schema, a FastAPI API and Power BI.",
    "market-pipline": "MARKET_OS: real-time market data from Binance and Alpha Vantage through Kafka and PySpark into S3, Redshift and a Streamlit dashboard.",
    "graduation-project": "EdgeGuard: ML intrusion detection on a Raspberry Pi 5 combining Snort 3 with a Random Forest and a 0–100 risk score.",
    "KAUST-Ai-project": "KAUST Academy AI labs: EDA, regression, classification, PyTorch neural networks and unsupervised learning.",
    "e2su.github.io": "Source code of this portfolio site.",
    "Analysing_Datasets": "Workspace for exploratory analysis of public datasets (in progress).",
  },
  languages: [
    { name: "Arabic", level: "Native" },
    { name: "English", level: "IELTS Academic 6.0 (Jul 2026)" },
  ],

  process: [
    { step: "01", title: "Map the data flow", text: "Every project starts with an architecture diagram, from source to dashboard." },
    { step: "02", title: "Test it", text: "pytest suites and GitHub Actions CI, including end-to-end runs against real PostgreSQL." },
    { step: "03", title: "Document & deploy", text: "Step-by-step READMEs, Docker Compose stacks, a 24/7 AWS deployment guide and Terraform." },
  ],

  // Labels for the fixed parts of the page
  ui: {
    "nav.about": "About",
    "nav.work": "Work",
    "nav.demo": "Demo",
    "nav.journey": "Journey",
    "nav.github": "GitHub",
    "nav.contact": "Contact",
    "nav.hire": "Hire me",
    "nav.language": "عربي",
    "nav.languageLabel": "Switch to Arabic",
    "hero.pill": "Open to data engineering roles",
    "hero.greeting": "Hi, I'm",
    "hero.build": "— I build",
    "hero.viewWork": "View my work",
    "hero.talk": "Let's talk",
    "marquee.caption": "Tools I've used in my projects",
    "about.eyebrow": "About",
    "about.title": 'Computer engineer.<br /><span class="gradient-text">Data engineer</span> by choice.',
    "services.eyebrow": "What I do",
    "services.title": 'From <span class="gradient-text">live data streams</span><br />to trained models.',
    "work.eyebrow": "Projects",
    "work.title": 'Things I\'ve <span class="gradient-text">built</span>.',
    "work.all": "All",
    "work.category.data": "Data",
    "work.category.ai": "AI & Security",
    "work.category.web": "Web",
    "work.caseStudy": "View case study",
    "case.problem": "The problem",
    "case.architecture": "Architecture",
    "case.built": "What I built",
    "case.results": "Results",
    "case.code": "View code",
    "case.video": "Watch on YouTube",
    "case.close": "Close",
    "certs.view": "View certificate",
    "demo.eyebrow": "Try it",
    "demo.title": 'EdgeGuard <span class="gradient-text">risk engine</span>.',
    "demo.intro": "Pick a traffic class to see how EdgeGuard scores it. The scores and severity tiers are the real ones from the project's inference engine.",
    "demo.score": "Risk score",
    "demo.level": "Severity",
    "demo.note": "If the model is less than 60% confident, EdgeGuard escalates the risk to 95 — uncertainty is treated as dangerous.",
    "journey.eyebrow": "Journey",
    "journey.title": 'Education &amp; <span class="gradient-text">experience</span>.',
    "certs.eyebrow": "Credentials",
    "certs.title": 'Certifications &amp; <span class="gradient-text">languages</span>.',
    "github.eyebrow": "Live from GitHub",
    "github.title": 'What I\'m <span class="gradient-text">pushing</span> right now.',
    "github.repos": "Public repositories",
    "github.languages": "Languages",
    "github.recent": "Recently updated",
    "github.profile": "View GitHub profile",
    "github.error": "GitHub couldn't be reached right now.",
    "github.noDescription": "No description yet.",
    "process.eyebrow": "How I build",
    "process.title": 'Designed, tested, <span class="gradient-text">documented</span>.',
    "contact.eyebrow": "Contact",
    "contact.title": 'Let\'s build something<br /><span class="gradient-text">together.</span>',
    "contact.email": "Email me",
    "contact.cv": "Download CV",
    "form.name": "Name",
    "form.namePlaceholder": "Your name",
    "form.email": "Email",
    "form.emailPlaceholder": "you@company.com",
    "form.message": "Message",
    "form.messagePlaceholder": "Tell me about the role or project…",
    "form.send": "Send message",
    "form.invalid": "Please fill in every field with a valid email.",
    "form.opening": "Opening your email app… thanks!",
    "form.subject": "Message from {name} via your portfolio",
  },
};
